### ISSUE TITLE
Requiring the CodeMirror Mode

### ISSUE THREAD

**Issue by rgbkrk** [ForbesLindesay/react-code-mirror#17]
In the example you show `require`ing the mode in your index.js, before `React` gets its hands on the `CodeMirror` component. For my case, I need to be able to set the mode dynamically. The way I'm doing this for the component that has a CodeMirror instance is to require the mode in `componentWillMount`. This works for me, especially since I have multiple CodeMirror instances on the page, though I'm wondering if maybe there's a better approach.

**Comment by ForbesLindesay** [comment]
I assume if that is working for you, you are either using a very different environment to browserify/webpack or you are actually requiring the modules somewhere else without realising it.  The reason they must be required separately is so that browserify etc. can statically analyse the code and know which modules to load.

**Comment by rgbkrk** [comment]
I'm using them in electron. The reason why it changes is that at runtime different languages can be selected.

**Comment by ForbesLindesay** [comment]
Ah, I think electron will let you require extra modules at runtime.  This is not the norm though, so it makes sense to force most people to require all the modes that they **might** use  up front.  It is still possible to set the mode dynamically, just only from the set of modes that have already been loaded.
